PACKAGE_NAME="elgato-gchd"
PACKAGE_VERSION="0.2.0"
BUILT_MODULE_NAME[0]="elgato_gchd"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
